name: gawr-remove-apikey-action
description: GAWR ApiKey Management Tool
author: Digitaal Vlaanderen
inputs:
  apikey:
    description: 'ApiKey'
    required: true

  env-tst:
    description: 'Test'
    required: true
   
  env-stg:
    description: 'Staging'
    required: true
   
  env-prd:
    description: 'Production'
    required: true

  aws-tst-access-key-id:
    description: 'AWS Acces Key Id Test ENV'
    required: true
    
  aws-tst-secret-access-key:
    description: 'AWS Secret Key Test ENV'
    required: true
    
  aws-tst-region-name:
    description: 'AWS Region name Test ENV'
    required: false
    default: 'eu-west-1'

  aws-tst-api-id:
    description: 'AWS Test api id'
    required: true

  aws-tst-stage-name:
    description: 'AWS Test stage name'
    required: true

  aws-stg-access-key-id:
    description: 'AWS Acces Key Id Staging ENV'
    required: true
    
  aws-stg-secret-access-key:
    description: 'AWS Secret Key Staging ENV'
    required: true
    
  aws-stg-region-name:
    description: 'AWS Region name Staging ENV'
    required: false
    default: 'eu-west-1'

  aws-stg-api-id:
    description: 'AWS Staging api id'
    required: true

  aws-stg-stage-name:
    description: 'AWS Staging stage name'
    required: true

  aws-prd-access-key-id:
    description: 'AWS Acces Key Id Production ENV'
    required: true
    
  aws-prd-secret-access-key:
    description: 'AWS Secret Key Production ENV'
    required: true
    
  aws-prd-region-name:
    description: 'AWS Region name Production ENV'
    required: false
    default: 'eu-west-1'

  aws-prd-api-id:
    description: 'AWS Production api id'
    required: true

  aws-prd-stage-name:
    description: 'AWS Production stage name'
    required: true

runs:
  using: 'docker'
  image: 'docker://ghcr.io/informatievlaanderen/gawr-api-key-action:2.0.0-remove'
  args:
    - ${{ inputs.apikey }}
    - ${{ inputs.env-tst }}
    - ${{ inputs.aws-tst-access-key-id}}
    - ${{ inputs.aws-tst-secret-access-key}}
    - ${{ inputs.aws-tst-region-name}}
    - ${{ inputs.aws-tst-api-id }}
    - ${{ inputs.aws-tst-stage-name }}
    - ${{ inputs.env-stg }}
    - ${{ inputs.aws-stg-access-key-id}}
    - ${{ inputs.aws-stg-secret-access-key}}
    - ${{ inputs.aws-stg-region-name}}
    - ${{ inputs.aws-stg-api-id }}
    - ${{ inputs.aws-stg-stage-name }}
    - ${{ inputs.env-prd }}
    - ${{ inputs.aws-prd-access-key-id}}
    - ${{ inputs.aws-prd-secret-access-key}}
    - ${{ inputs.aws-prd-region-name}}
    - ${{ inputs.aws-prd-api-id }}
    - ${{ inputs.aws-prd-stage-name }}
branding:
  icon: 'terminal'
  color: 'yellow'
