name: gawr-add-apikey-action
description: GAWR ApiKey Management Tool
author: Digitaal Vlaanderen
inputs:
  client:
    description: 'clientname'
    required: true

  email:
    description: 'email'
    required: true
  
  plan:
    description: 'options ["anon", "abuse", "standard", "unlimited"]'
    required: true

  access-sync:
    description: 'Grant sync access'
    required: true

  access-road-registry:
    description: 'Grant road-registry access'
    required: true

  revoke-access:
    description: 'Revoke access'
    required: false

  env-tst:
    description: 'Test'
    required: true
   
  env-stg:
    description: 'Staging'
    required: true
   
  env-prd:
    description: 'Production'
    required: true

  aws-tst-access-key-id:
    description: 'AWS Acces Key Id Test ENV'
    required: true
    
  aws-tst-secret-access-key:
    description: 'AWS Secret Key Test ENV'
    required: true
    
  aws-tst-region-name:
    description: 'AWS Region name Test ENV'
    required: false
    default: 'eu-west-1'

  aws-stg-access-key-id:
    description: 'AWS Acces Key Id Staging ENV'
    required: true
    
  aws-stg-secret-access-key:
    description: 'AWS Secret Key Staging ENV'
    required: true
    
  aws-stg-region-name:
    description: 'AWS Region name Staging ENV'
    required: false
    default: 'eu-west-1'

  aws-prd-access-key-id:
    description: 'AWS Acces Key Id Production ENV'
    required: true
    
  aws-prd-secret-access-key:
    description: 'AWS Secret Key Production ENV'
    required: true
    
  aws-prd-region-name:
    description: 'AWS Region name Production ENV'
    required: false
    default: 'eu-west-1'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.client }}
    - ${{ inputs.email }}
    - ${{ inputs.plan }}
    - ${{ inputs.access-sync }}
    - ${{ inputs.access-road-registry }}
    - ${{ inputs.env-tst }}
    - ${{ inputs.env-stg }}
    - ${{ inputs.env-prd }}
    - ${{ inputs.aws-tst-access-key-id}}
    - ${{ inputs.aws-tst-secret-access-key}}
    - ${{ inputs.aws-tst-region-name}}
    - ${{ inputs.aws-stg-access-key-id}}
    - ${{ inputs.aws-stg-secret-access-key}}
    - ${{ inputs.aws-stg-region-name}}
    - ${{ inputs.aws-prd-access-key-id}}
    - ${{ inputs.aws-prd-secret-access-key}}
    - ${{ inputs.aws-prd-region-name}}
    - ${{ inputs.revoke-access }}
branding:
  icon: 'terminal'
  color: 'yellow'
